version: '3'

services:
  webapp:
    build: .
    container_name: privacy-policy-analyzer
    ports:
      - "5000:5000"
    volumes:
      - .:/app  
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
      - MONGODB_HOST=mongodb
      - MONGODB_DB=CS30
    depends_on:
      - mongodb
    restart: no
    
  mongodb:
    image: mongo:latest
    container_name: privacy-policy-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: